#ifndef STUDENT_H
#define STUDENT_H

#include <QMainWindow> // <<< CHANGED from QDialog
#include <QStringList>
#include <QStandardItemModel>

namespace Ui {
// The UI class name generated by uic based on student.ui
class student;
}

class student : public QMainWindow // <<< CHANGED base class
{
    Q_OBJECT

public:
    // Constructor still accepts studentData
    explicit student(const QStringList &studentData, QWidget *parent = nullptr);
    ~student();
public slots:
    void on_logout_clicked();
    void on_offer_clicked();
    void on_viewprofile_clicked();
    void on_reg_clicked();
    void on_view_clicked();
    void on_withdraw_clicked();
    void on_viewassignments_clicked();
private:
    Ui::student *ui;
    QStringList m_studentData;

    void displayStudentDetails();
    QStringList getAssignmentsForCourse(const QString &courseCode);
    void downloadAssignmentFile(const QString &fileName);
    QStringList getRegisteredCourseCodes(const QString &studentName);
    QString getCourseTitle(const QString &courseCode);
};

#endif // STUDENT_H
